blank_issues_enabled: false
contact_links:
  - name: Q&A, tips, and support
    url: https://github.com/divyamohan1993/devops-shell-scripts/discussions
    about: Please use Discussions for general questions and how‑to help.
